env:
  browser: true
extends:
  - "eslint:recommended"
  - "plugin:vue/essential"
parserOptions:
  ecmaVersion: 12
  parser: "esprima"
  sourceType: module
plugins:
  - vue
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
